name = "Server Pack"
author = "Jurn Wubben"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67df10d741c444cc6ff9abc0fbf3b3d124b478dd316629eb44e64277e87340f4"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
