name = "Server Pack"
author = "Jurn Wubben"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe0975a5c90084cd0cedf68151e4f6f2180ae83fe509846f745c14addf072997"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
