name = "Server Pack"
author = "Jurn Wubben"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "732782546fa44276aaae7cc0fc4e5171133d520b4d31e7706067525325d208a3"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
