name = "Server Pack"
author = "Jurn Wubben"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3de8fc0787a0f95910b64c983f4523e61acad20f5477b5f10d56e9db927ffe22"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
