name = "Server Pack"
author = "Jurn Wubben"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb54dc20f404e9eaa3f6c5eff99b2fbbdc1ecb04397ec0eb59cf15059ead8d5"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
